# PII Patterns Configuration for AiGov PromptGate
# Admin Portal에서 패턴을 정의하면 이 파일이 자동으로 업데이트됩니다

[pii_patterns]

# 주민등록번호 패턴
ssn = [
    { regex = '''\b\d{6}-[1-4]\d{6}\b''', severity = "high", description = "일반 주민등록번호" },
    { regex = '''\b\d{6}[1-4]\d{6}\b''', severity = "high", description = "하이픈 없는 주민등록번호" },
    { regex = '''\b\d{6}-[5-8]\d{6}\b''', severity = "high", description = "외국인등록번호" },
    { regex = '''\b\d{6}[5-8]\d{6}\b''', severity = "high", description = "하이픈 없는 외국인등록번호" },
]

# 휴대폰 번호 패턴
phone = [
    { regex = '''\b01[016789]-?\d{3,4}-?\d{4}\b''', severity = "high", description = "휴대폰 번호" },
    { regex = '''\b01[016789]\d{7,8}\b''', severity = "high", description = "하이픈 없는 휴대폰 번호" },
    { regex = '''\b0\d{1,2}-?\d{3,4}-?\d{4}\b''', severity = "medium", description = "일반 전화번호" },
    { regex = '''\b0\d{9,10}\b''', severity = "medium", description = "하이픈 없는 일반 전화번호" },
    { regex = '''\+\d{1,3}-?\d{1,4}-?\d{3,4}-?\d{4}\b''', severity = "medium", description = "국제 전화번호" },
]

# 이메일 주소 패턴
email = [
    { regex = '''\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b''', severity = "high", description = "일반 이메일 주소" },
    { regex = '''\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.(co\.kr|go\.kr|ac\.kr|or\.kr)\b''', severity = "high", description = "한국 도메인 이메일" },
    { regex = '''\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.(com|net|org|edu|gov)\b''', severity = "high", description = "국제 도메인 이메일" },
]

# 신용카드 번호 패턴
credit_card = [
    { regex = '''\b\d{4}[-\s]?\d{4}[-\s]?\d{4}[-\s]?\d{4}\b''', severity = "high", description = "16자리 신용카드 번호" },
    { regex = '''\b\d{4}[-\s]?\d{4}[-\s]?\d{4}[-\s]?\d{4}[-\s]?\d{3}\b''', severity = "high", description = "19자리 신용카드 번호" },
    { regex = '''\b\d{4}[-\s]?\d{6}[-\s]?\d{5}\b''', severity = "high", description = "15자리 신용카드 번호" },
]

# 은행 계좌번호 패턴
bank_account = [
    { regex = '''\b\d{3}-\d{2}-\d{6}\b''', severity = "high", description = "6자리 계좌번호" },
    { regex = '''\b\d{3}-\d{2}-\d{7}\b''', severity = "high", description = "7자리 계좌번호" },
    { regex = '''\b\d{3}-\d{2}-\d{8}\b''', severity = "high", description = "8자리 계좌번호" },
    { regex = '''\b\d{3}-\d{2}-\d{9}\b''', severity = "high", description = "9자리 계좌번호" },
    { regex = '''\b\d{3}-\d{2}-\d{10}\b''', severity = "high", description = "10자리 계좌번호" },
    { regex = '''\b\d{3}-\d{2}-\d{11}\b''', severity = "high", description = "11자리 계좌번호" },
    { regex = '''\b\d{3}-\d{2}-\d{12}\b''', severity = "high", description = "12자리 계좌번호" },
    { regex = '''\b\d{3}-\d{2}-\d{13}\b''', severity = "high", description = "13자리 계좌번호" },
    { regex = '''\b\d{3}-\d{2}-\d{14}\b''', severity = "high", description = "14자리 계좌번호" },
    { regex = '''\b\d{3}-\d{2}-\d{15}\b''', severity = "high", description = "15자리 계좌번호" },
]

# IP 주소 패턴
ip_address = [
    { regex = '''\b(?:[0-9]{1,3}\.){3}[0-9]{1,3}\b''', severity = "medium", description = "IPv4 주소" },
    { regex = '''\b(?:[0-9a-fA-F]{1,4}:){7}[0-9a-fA-F]{1,4}\b''', severity = "medium", description = "IPv6 주소" },
    { regex = '''\b(?:[0-9a-fA-F]{1,4}:){1,7}:\b''', severity = "medium", description = "축약된 IPv6 주소" },
]

# MAC 주소 패턴
mac_address = [
    { regex = '''\b(?:[0-9a-fA-F]{2}[:-]){5}[0-9a-fA-F]{2}\b''', severity = "medium", description = "MAC 주소" },
    { regex = '''\b(?:[0-9a-fA-F]{2}[:-]){5}[0-9a-fA-F]{2}\b''', severity = "medium", description = "MAC 주소 (콜론 구분)" },
]

# 생년월일 패턴
date_of_birth = [
    { regex = '''\b(19|20)\d{2}-(0[1-9]|1[0-2])-(0[1-9]|[12]\d|3[01])\b''', severity = "medium", description = "YYYY-MM-DD 형식" },
    { regex = '''\b(19|20)\d{2}\.(0[1-9]|1[0-2])\.(0[1-9]|[12]\d|3[01])\b''', severity = "medium", description = "YYYY.MM.DD 형식" },
    { regex = '''\b(19|20)\d{2}/(0[1-9]|1[0-2])/(0[1-9]|[12]\d|3[01])\b''', severity = "medium", description = "YYYY/MM/DD 형식" },
    { regex = '''\b(0[1-9]|[12]\d|3[01])-(0[1-9]|1[0-2])-(19|20)\d{2}\b''', severity = "medium", description = "DD-MM-YYYY 형식" },
    { regex = '''\b(0[1-9]|[12]\d|3[01])\.(0[1-9]|1[0-2])\.(19|20)\d{2}\b''', severity = "medium", description = "DD.MM.YYYY 형식" },
]

# 주소 패턴
address = [
    { regex = '''\b(서울|부산|대구|인천|광주|대전|울산|세종|경기|강원|충북|충남|전북|전남|경북|경남|제주)\s+[가-힣\s\d-]+''', severity = "medium", description = "한국 시도 주소" },
    { regex = '''\b\d{5}\b''', severity = "low", description = "우편번호" },
    { regex = '''\b[가-힣]+시\s+[가-힣]+구\s+[가-힣]+동\b''', severity = "medium", description = "시구동 주소" },
    { regex = '''\b[가-힣]+도\s+[가-힣]+시\s+[가-힣]+구\b''', severity = "medium", description = "도시구 주소" },
]

# 이름 패턴
name = [
    { regex = '''\b[가-힣]{2,4}\b''', severity = "low", description = "한국 이름 (2-4글자)" },
    { regex = '''\b[A-Z][a-z]+\s+[A-Z][a-z]+\b''', severity = "low", description = "영문 이름 (성+이름)" },
    { regex = '''\b[가-힣]{2,4}\s+[가-힣]{2,4}\b''', severity = "low", description = "한국 이름 (성+이름)" },
]

# 여권 번호 패턴
passport = [
    { regex = '''\b[A-Z]{1,2}\d{6,9}\b''', severity = "high", description = "여권 번호" },
    { regex = '''\b\d{9}\b''', severity = "high", description = "9자리 여권 번호" },
    { regex = '''\b[A-Z]\d{8}\b''', severity = "high", description = "영문+8자리 여권 번호" },
]

# 운전면허 번호 패턴
driver_license = [
    { regex = '''\b\d{2}-\d{2}-\d{6}-\d{2}\b''', severity = "high", description = "운전면허 번호" },
    { regex = '''\b\d{2}-\d{2}-\d{6}-\d{2}\b''', severity = "high", description = "하이픈 없는 운전면허 번호" },
    { regex = '''\b\d{12}\b''', severity = "high", description = "12자리 운전면허 번호" },
]

# 기타 민감 정보 패턴
other = [
    { regex = '''\b[A-Za-z0-9+/]{40,}={0,2}\b''', severity = "medium", description = "Base64 인코딩된 데이터" },
    { regex = '''\b0x[0-9a-fA-F]{32,}\b''', severity = "medium", description = "Hex 인코딩된 데이터" },
    { regex = '''\b[A-Za-z0-9]{20,}\b''', severity = "low", description = "긴 알파벳 숫자 조합" },
]
