# Rebuff는 Next.js 기반 (Node.js)
FROM node:18

WORKDIR /app

# 프론트엔드 소스 코드 복사
COPY frontend/package*.json ./
RUN npm install

COPY frontend/ .

RUN npm run build

EXPOSE 8080
CMD ["npm", "run", "start"]
